#!/bin/sh

# get changed .php files
FILES=$(git diff --name-only HEAD master | grep .php);

# run phpcs
if [ ! -z "$FILES" ]; then
	printf "Running Code Sniffer..."
	vendor/bin/phpcs $FILES --standard=vendor/zenify/coding-standard/src/ZenifyCodingStandard/ruleset.xml

	if [ $? -ne 0 ]
	then
		printf "\033[0;41;37mFix coding standards before commit!\033[0m\n"
		exit 1
	fi
fi
